version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - 443:443