version: "3"
volumes:
  postgres-data:
    driver: local

services:
  app: &rails_base
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  jobs:
    ports: []
    <<: *rails_base
    command: rails jobs:work
  webpacker:
    ports: []
    <<: *rails_base
    command: ./bin/webpack-dev-server
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/DockerFile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
