version: "3"
services:
  web: &rails_base
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/postgres
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  jobs:
    ports: []
    <<: *rails_base
    command: rails jobs:work
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - /Users/mihail/Library/Application Support/mkcert:/etc/local_cert
      - /Users/mihail/dev/optimization/rails-optimization-task5/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dockerhost
  db:
    image: postgres
    ports:
    - "5432:5432"
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
