version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    network_mode: host
    volumes:
      - ./confs/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/:/etc/nginx/certs:ro
