version: "3"

services:
  nginx:
    image: nginx
    container_name: localhost
    network_mode: host
    volumes:
      - ./localhost.conf:/etc/nginx/conf.d/localhost.conf:ro
      - /home/bav/.mkcert:/etc/nginx/certs:ro
